export const SUCCESS = "SUCCESS";
export const SET_SUCCESS = "SET_SUCCESS";
export const TOGGLE_USER = "TOGGLE_USER";

export const FAILURE = "FAILURE";
export const SET_USERS = "SET_USERS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SET_USER_WISHLIST = "SET_USER_WISHLIST";
export const SET_PROMOTIONS = "SET_PROMOTIONS";

export const ADD_PROFILE = "ADD_PROFILE";
export const MATERIALS_IS_FETCHING = "MATERIALS_IS_FETCHING";
export const UPDATE_MATERIALS = "UPDATE_MATERIALS";
export const SET_MATERIAL_ERROR = "SET_MATERIAL_ERROR";
export const SET_SETTINGS = "SET_SETTINGS";
export const SETTINGS_IS_FETCHING = "SETTINGS_IS_FETCHING";
export const SET_MATERIAL_TYPE = "SET_MATERIAL_TYPE";
export const SET_SIMPLE_SEARCH_KEYWORD = "SET_SIMPLE_SEARCH_KEYWORD";
export const TOGGLE_FILTER_SECTION = "TOGGLE_FILTER_SECTION";
export const SET_SEARCH_TYPE = "SET_SEARCH_TYPE";
export const UPDATE_SELECTED_COLUMNS = "UPDATE_SELECTED_COLUMNS";
export const UPDATE_ORDER_BY = "UPDATE_ORDER_BY";
export const CREATE_ADVANCED_SEARCH_FIELDS = "CREATE_ADVANCED_SEARCH_FIELDS";
export const ADD_ADVANCED_SEARCH_FIELDS = "ADD_ADVANCED_SEARCH_FIELDS";
export const REMOVE_ADVANCED_SEARCH_FIELDS = "REMOVE_ADVANCED_SEARCH_FIELDS";
export const RESET_ADVANCED_SEARCH_FIELDS = "RESET_ADVANCED_SEARCH_FIELDS";
export const UPDATE_ADVANCED_SEARCH_FIELDS = "UPDATE_ADVANCED_SEARCH_FIELDS";
export const USERS_IS_FETCHING = "USERS_IS_FETCHING";
export const UPDATE_USERS = "UPDATE_USERS";
export const USERS_SEARCH_KEYWORD = "USERS_SEARCH_KEYWORD";
export const UPDATE_USERS_SELECTED_COLUMNS = "UPDATE_USERS_SELECTED_COLUMNS";
export const UPDATE_USERS_ORDER_BY = "UPDATE_USERS_ORDER_BY";
export const SET_SELECTED_USER = "SET_SELECTED_USER";
export const SET_MATERIAL = "SET_MATERIAL";
export const RESET_MATERIALS = "RESET_MATERIALS";
export const RAISE_FIELDS_ERROR = "RAISE_FIELDS_ERROR";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";

export const REMOVE_PROFILE = "REMOVE_PROFILE";

export const USER_INPUT_CHANGE = "USER_INPUT_CHANGE";

export const USER_INPUT_SUBMIT = "USER_INPUT_SUBMIT";
export const USER_LOGOUT = "USER_LOGOUT";

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";

export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const USERS_IS_LOADING = "USERS_IS_LOADING";

export const GET_DRIVERS_SUCCESS = "GET_DRIVERS_SUCCESS";

export const GET_REVIEWERS_SUCCESS = "GET_REVIEWERS_SUCCESS";

export const GET_INSPECTIONS_SUCCESS = "GET_INSPECTIONS_SUCCESS";

export const GET_INSPECTIONS_FAILURE = "GET_INSPECTIONS_FAILURE";

export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";

export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

export const GET_SUPER_ADMINS_SUCCESS = "GET_SUPER_ADMINS_SUCCESS";

export const FETCHING_DATA = "SUPER_ADMINS/FETCHING_DATA";

export const FETCHING_DATA_FAILED = "SUPER_ADMINS/FETCHING_DATA_FAILED";

export const GET_REVIEWERS_FOR_SUPER_ADMINS_SUCCESS =
    "SUPER_ADMINS/GET_REVIEWERS_SUCCESS";

export const GET_DRIVERS_FOR_SUPER_ADMINS_SUCCESS =
    "SUPER_ADMINS/GET_DRIVERS_SUCCESS";

export const GET_INSPECTIONS_FOR_REVIEWERS_SUCCESS =
    "REVIEWERS/GET_INSPECTIONS_SUCCESS";

export const GET_TERMS_SUCCESS = "GET_TERMS_SUCCESS";

export const GET_TERMS_FAILURE = "GET_TERMS_FAILURE";

export const GET_ORACLE_DRIVERS_SUCCESS = "GET_ORACLE_DRIVERS_SUCCESS";

export const GET_ORACLE_DRIVERS_FAILURE = "GET_ORACLE_DRIVERS_FAILURE";

export const GET_FAQS_SUCCESS = "GET_FAQS_SUCCESS";

export const GET_FAQS_FAILURE = "GET_FAQS_FAILURE";
export const SELECT_USER = "SELECT_USER";
export const GET_VEHICLES_SUCCESS = "GET_VEHICLES_SUCCESS";
export const GET_REVIEWER_DRIVERS_SUCCESS = "GET_REVIEWER_DRIVERS_SUCCESS";
export const GET_VEHICLES_INSPECTIONS_SUCCESS =
    "GET_VEHICLES_INSPECTIONS_SUCCESS";
export const SET_ERROR = "SET_ERROR";
export const APP_IS_LOADING = "APP_IS_LOADING";
export const SET_SUCCESS_MESSAGE = "SET_SUCCESS_MESSAGE";
export const SET_STATS_SUCCESS = "SET_STATS_SUCCESS";
export const SET_RECENT_VEHICLES_SUCCESS = "SET_RECENT_VEHICLES_SUCCESS";
export const SET_SELECTED_DATE_SUCCESS = "SET_SELECTED_DATE_SUCCESS";
export const GET_INSPECTION_SUCCESS = "GET_INSPECTION_SUCCESS";
export const GET_INSPECTION_DETAILS_SUCCESS = "GET_INSPECTION_DETAILS_SUCCESS";
export const SET_QUESTIONS_LANGUAGE = "SET_QUESTIONS_LANGUAGE";
export const SET_DASHBOARD_IS_LOADING = "SET_DASHBOARD_IS_LOADING";
export const SET_SHOW_LOAD_MORE = "SET_SHOW_LOAD_MORE";
export const SHOW_MORE_FILTERS = "SHOW_MORE_FILTERS";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAILURE = "GET_USER_BY_ID_FAILURE";
export const UPDATE_SELECTED_FILTERS_SINGLE = "UPDATE_SELECTED_FILTERS_SINGLE";
export const UPDATE_SELECTED_FILTERS_MULTI = "UPDATE_SELECTED_FILTERS_MULTI";
export const RESET_SELECTED_FILTERS = "RESET_SELECTED_FILTERS";
export const REPLACE_SELECTED_FILTERS = "REPLACE_SELECTED_FILTERS";